"""Update jobs table schema to match JobModel

Revision ID: c1687ac52920
Revises: 
Create Date: 2025-05-21 13:33:17.368160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1687ac52920'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('salary', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('is_remote', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('jobs', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('jobs', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               nullable=False)
    op.alter_column('jobs', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('jobs', 'date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'company',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_remote')
    op.drop_column('jobs', 'salary')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###
